project:
  type: website
  output-dir: docs

website:
  title: "Taylor Bacon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

