project:
  type: website
  output-dir: docs

website:
  title: "Taylor Bacon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - Media.qmd
      - text: CV
        href: cv/CV.qmd


format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

